import type {
  ConfidenceCalculator,
  ConfidenceResult,
  EvaluationInput,
  Explainer,
  ExplanationInput,
  ExplanationResult,
  GeneratedRecommendation,
  RecommendationGenerator,
  RuleEvaluationResult,
  RuleEvaluator,
} from "./services";
import type { RuleTrace } from "./types";

// PLACEHOLDER implementations. They exist so the container/lifecycle has
// something structurally valid to carry. They do NOT decide real stewardship
// outcomes — real rules, thresholds, and confidence formulas require customer
// discovery (ai-architecture.md) and are excluded from E5.

/**
 * No stewardship rules configured. Returns a conservative, clearly-marked inert
 * result. `rest` (reduce visitor pressure) is chosen as the low-regret default,
 * NOT as a validated rule.
 */
export class PlaceholderRuleEvaluator implements RuleEvaluator {
  evaluate(input: EvaluationInput): RuleEvaluationResult {
    const ruleTrace: RuleTrace = {
      rules: [
        {
          id: "placeholder-default",
          note: "No stewardship rules configured; conservative default pending discovery.",
          matched: true,
        },
      ],
      inputRefs: {
        observationIds: input.observationIds,
        signalIds: [
          ...(input.environmentalSignalIds ?? []),
          ...(input.operationalSignalIds ?? []),
        ],
        landscapeAreaId: input.landscapeAreaId ?? null,
      },
      placeholder: true,
    };
    return {
      action: "rest",
      attention: "monitor",
      ruleTrace,
      evidence: [],
      missingEvidence:
        "Placeholder evaluation — no rules or signals were evaluated.",
      alternative: null,
    };
  }
}

/** Production confidence formula deferred; always Unknown. */
export class PlaceholderConfidenceCalculator implements ConfidenceCalculator {
  calculate(): ConfidenceResult {
    return {
      level: "unknown",
      reason:
        "Placeholder confidence — production formula deferred (ai-architecture.md); requires discovery.",
    };
  }
}

/**
 * Deterministic structured-rationale explainer (no LLM). This is BOTH the E5
 * placeholder AND the future LLM's failure-path fallback: a recommendation
 * always ships with its charter-required "why", even at low/unknown confidence.
 */
export class DeterministicExplainer implements Explainer {
  explain(input: ExplanationInput): ExplanationResult {
    const lines = [
      `Recommended action: ${input.action} (attention: ${input.attention}).`,
      `Confidence: ${input.confidence.level} — ${input.confidence.reason}`,
      ...input.ruleTrace.rules.map((r) => `Rule ${r.id}: ${r.note}`),
      ...(input.evidence.length
        ? [`Evidence: ${input.evidence.join("; ")}`]
        : []),
      ...(input.missingEvidence ? [`Missing evidence: ${input.missingEvidence}`] : []),
    ];
    return { text: lines.join("\n"), source: "deterministic" };
  }
}

/** Composes the placeholder services into a `generated`-ready recommendation. */
export class PlaceholderRecommendationGenerator
  implements RecommendationGenerator
{
  constructor(
    private readonly rules: RuleEvaluator = new PlaceholderRuleEvaluator(),
    private readonly confidence: ConfidenceCalculator = new PlaceholderConfidenceCalculator(),
    private readonly explainer: Explainer = new DeterministicExplainer(),
  ) {}

  async generate(input: EvaluationInput): Promise<GeneratedRecommendation> {
    const evaluation = await this.rules.evaluate(input);
    const confidence = await this.confidence.calculate(input, evaluation);
    const explanation = await this.explainer.explain({
      action: evaluation.action,
      attention: evaluation.attention,
      confidence,
      ruleTrace: evaluation.ruleTrace,
      evidence: evaluation.evidence,
      missingEvidence: evaluation.missingEvidence,
    });

    return {
      action: evaluation.action,
      attention: evaluation.attention,
      title: `Placeholder recommendation (${evaluation.action})`,
      shortReason:
        "Generated by placeholder services; not a validated stewardship decision.",
      confidence: confidence.level,
      confidenceReason: confidence.reason,
      explanation: explanation.text,
      explanationSource: explanation.source,
      ruleTrace: evaluation.ruleTrace,
      evidence: evaluation.evidence,
      missingEvidence: evaluation.missingEvidence ?? null,
      alternative: evaluation.alternative ?? null,
      landscapeAreaId: input.landscapeAreaId ?? null,
    };
  }
}
